# Generated by Django 2.2.2 on 2019-06-19 13:19

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoanEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=books.models.LoanStatus('requested'), max_length=2)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=django_fsm.FSMField(choices=[('AV', 'available'), ('OL', 'on loan'), ('RQ', 'requested'), ('NA', 'not available')], default=books.models.LoanStatus('available'), max_length=50),
        ),
        migrations.DeleteModel(
            name='BookLoan',
        ),
        migrations.AddField(
            model_name='bookloanevent',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AddField(
            model_name='bookloanevent',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
